baseURL = "https://www.rustybower.com/"
languageCode = "en-us"
title = "Rusty Bower"
#theme = "PaperMod" 
theme = "ananke"

# Optional but useful
pagination.pagerSize = 10

[params]
  author = "Rusty Bower"
  description = "Security engineering, systems, and thoughts."
