baseURL = "https://www.rustybower.com/"
languageCode = "en-us"
title = "Rusty Bower"
theme = "stack"

pagination.pagerSize = 10

[params]
  author = "Rusty Bower"
  description = "Security engineering, systems, and thoughts."
  mainSections = ["posts"]
  rssFullContent = true

  [params.footer]
    since = 2026

  [params.sidebar]
    compact = false

  [params.article]
    toc = true
    readingTime = true

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "home"

  [[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 2
    [menu.main.params]
      icon = "archives"

  [[menu.main]]
    name = "Search"
    url = "/search"
    weight = 3
    [menu.main.params]
      icon = "search"

[outputs]
  home = ["HTML", "RSS"]
